version: "3.0"

services:
  db:
    image: mongo
    container_name: mcube-masanet-coding-test-db
    restart: unless-stopped
    volumes:
      - ./db/:/data/db
      - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  dbbo:
    image: mongo-express
    container_name: mcube-masanet-coding-test-dbbo
    restart: unless-stopped
    ports:
      - ${DB_BACKOFFICE_PORT}:${DB_BACKOFFICE_PORT}
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@db:27017/

  api:
    build: ./api/
    container_name: mcube-masanet-coding-test-api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    command: npm run start
    environment:
      - API_PORT=${API_PORT}
      - APP_PORT=${APP_PORT}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - TMDB_API_KEY=${TMDB_API_KEY}
