version: "3.0"

services:
  api:
    build: ./api/
    container_name: mcube-masanet-coding-test-api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    command: npm run start
    environment:
      - API_PORT=${API_PORT}
      - APP_PORT=${APP_PORT}
